#!/usr/bin/env bash

origin=$(readlink -f "$(dirname "$0")")

exec 197<&0

pipe=/tmp/afl.$$.$RANDOM
mkfifo $pipe

libdl_so=/lib/x86_64-linux-gnu/libdl.so.2

if [ -f "$libdl_so" ]; then
    ln -fs "$libdl_so" libdl
fi
# Replace with the commented line below to gain access to Renode graphical interface
LD_LIBRARY_PATH="$(pwd)" renode --disable-xwt --console --hide-analyzers  -e "py \"sys.path.append('$origin/renode_mode'); import afl_renode\"; i @$1; py \"afl_renode.start_fuzzing()\"" <$pipe &
#LD_LIBRARY_PATH="$(pwd)" renode -e "py \"sys.path.append('$origin/renode_mode'); import afl_renode\"; i @$1; py \"afl_renode.start_fuzzing()\"" <$pipe &

exec >$pipe
rm $pipe
wait
